# =========================== Basic Settings ===========================
# machine info
num_gpus_per_job: 1  # number of gpus each job need
num_cpus_per_job: 1  # number of gpus each job need
num_hosts_per_job: 1
memory_per_job: 32  # number of gpus each job need
gpu_type: #'nvidia-tesla-p100'

# parameters
name: imnet_gated_conv_new_model_v100  # any name
model_restore: 'logs/release_imagenet_256' #'logs\small_Image_net_256'  # logs/places2_gated_conv
dataset: 'imagenet'  # 'tmnist', 'dtd', 'places2', 'celeba', 'imagenet', 'cityscapes'
random_crop: True  # Set to false when dataset is 'celebahq', meaning only resize the images to img_shapes, instead of crop img_shapes from a larger raw image. This is useful when you train on images with different resolutions like places2. In these cases, please set random_crop to true.
val: True  # true if you want to view validation results in tensorboard
log_dir: logs/retrain_imagenet_new_model_v102
#############################################################################################
# v100: changes activation fo the genconv to relu instead of elu - faster computational time?
#       changes sigmoid activation for the mask to tanh - zero centered activation
#       reduce filter number by 25% (from 48 to 36) - faster computational time?
##############################################################################################
#############################################################################################
# v101: changes activation fo the genconv to relu instead of elu - faster computational time?
#       changes sigmoid activation for the mask to tanh - zero centered activation
#       use pretrained parameters to see if the mask disappears.
##############################################################################################
#############################################################################################
# v102: changes activation fo the genconv to leaky_relu instead of elu - faster computational time?
#       use pretrained parameters to see if the mask disappears.
##############################################################################################
#############################################################################################
# v103: changes activation fo the genconv to leaky_relu instead of elu - faster computational time?
#       use pretrained parameters to see if the mask disappears.
#       reduce the input image shape to [128,128,3]
##############################################################################################
gan: 'sngan'
gan_loss_alpha: 1
gan_with_mask: True
discounted_mask: True
random_seed: False
padding: 'SAME'

# training
train_spe: 4000
max_iters: 100000000
viz_max_out: 10
val_psteps: 2000

# data
data_flist:
  # https://github.com/jiahuiyu/progressive_growing_of_gans_tf
  celebahq: [
    'data/celeba_hq/train_shuffled.flist',
    'data/celeba_hq/validation_static_view.flist'
  ]
  # http://mmlab.ie.cuhk.edu.hk/projects/celeba.html, please to use random_crop: True
  celeba: [
    'data/celeba/train_shuffled.flist',
    'data/celeba/validation_static_view.flist'
  ]
  # http://places2.csail.mit.edu/, please download the high-resolution dataset and use random_crop: True
  places2: [
    'data/places2/train_shuffled.flist',
    'data/places2/validation_static_view.flist'
  ]
  imagenetsmall: [
    './data_flist/train_shuffled_small.flist',
    './data_flist/valid_shuffled_small.flist',
  ]
  imagenet: [
    './data_flist/train_shuffled.flist',
    './data_flist/validation_static_view.flist',
  ]
  # http://www.image-net.org/, please use random_crop: True
#   imagenet: [
#     'data/imagenet/train_shuffled.flist',
#     'data/imagenet/validation_static_view.flist',
#   ]

static_view_size: 30
img_shapes: [128, 128, 3]
height: 64
width: 64
max_delta_height: 16
max_delta_width: 16
batch_size: 16
vertical_margin: 0
horizontal_margin: 0

# loss
ae_loss: True
l1_loss: True
l1_loss_alpha: 1

# to tune
guided: False
edge_threshold: 0.6
